Add configuration to native-image plugin
--allow-incomplete-classpath is needed because of the missing jar for javax.ejb.EJB:

Call path from entry point to org.apache.catalina.core.DefaultInstanceManager.populateAnnotationsCache(Class, Map):
	at org.apache.catalina.core.DefaultInstanceManager.populateAnnotationsCache(DefaultInstanceManager.java:300)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:173)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)

--report-unsupported-elements-at-runtime is needed because of:

Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1213)
Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory):
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1205)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53)

Both are not affecting this application